### PR TITLE
Small tweak to add more CSS control options

### PR DESCRIPTION
**Pull request by silverbucket**
Hello, I just wanted to add some stylings based on first or last entry in the commit list, so made this small tweak. ...ntrol

### CODE REVIEW

**Comment by alexbeletsky** [comment]
@silverbucket thanks a lot for this pull request.

But, I don't see big value in it, since you changing the HTML instead of applying applying the CSS on <li> items. With CSS you can easily match start:end elements, without introduction on any new classes.

**Comment by silverbucket** [comment]
Well, the downside is that with first or last-child, we won't have support for IE7 or lower, and maybe some other browsers. But, I see your point, maybe that's the more elegant solution.

**Comment by alexbeletsky** [comment]
Ok, I left small comments in code. Please consider to fix it, so I can merge that up :)

**Comment by silverbucket** [comment]
good points, I tidied the code up a bit. what do you think?

**Comment by alexbeletsky** [comment]
It's there :)

**Pull request merged**
